name: Deploy to production

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup go1.2x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.22
        id: go

      - name: Checkout code into Go module directory
        uses: actions/checkout@v2

      - name: Test
        run: make test
